package com.facebook.presto.operator;

import com.facebook.presto.common.Page;
import com.facebook.presto.spi.ConnectorMergeSink;

public interface MergeRowChangeProcessor
{
    int DEFAULT_CASE_OPERATION_NUMBER = -1;

    /**
     * Transform a page generated by an SQL MERGE operation into page of data columns and
     * operations. The SQL MERGE input page consists of the following:
     * <ul>
     *     <li>The write redistribution columns, if any</li>
     *     <li>For partitioned or bucketed tables, a hash value column</li>
     *     <li>The rowId column for the row from the target table if matched, or null if not matched</li>
     *     <li>The merge case row block</li>
     * </ul>
     * The output page consists of the following:
     * <ul>
     *     <li>All data columns, in table column order</li>
     *     <li>{@link ConnectorMergeSink#storeMergedRows The operation block}</li>
     *     <li>The rowId block</li>
     *     <li>The last column in the resulting page is 1 if the row is an insert
     *         derived from an update, and zero otherwise.</li>
     * </ul>
     * <p>
     * The {@link DeleteAndInsertMergeProcessor} implementation will transform each UPDATE
     * row into multiple rows: an INSERT row and a DELETE row.
     */
    Page transformPage(Page inputPage);
}
